noruh_backend/urls.py
from django.utils.translation import gettext as _
from django.contrib import admin
from django.urls import path, re_path, include

from rest_framework.documentation import include_docs_urls
from rest_auth.registration.views import VerifyEmailView

urlpatterns = [
    path('', include(('register.urls', 'register'), namespace='register')),
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),

    path('api/auth/', include('rest_framework_social_oauth2.urls')),

    path('api/', include(('register.api.urls', 'register-api'), namespace='register-api')),
    path('api/docs/', include_docs_urls(title='Noruh API Documentation')),
    path('api/payment/', include(('register.payment.urls', 'register-api-payment'), namespace='register-api-payment')),
    path('api/rest-auth/', include('rest_auth.urls')),
    path('api/rest-auth/accounts/', include('allauth.urls'), name='socialaccount_signup'),
    path('api/rest-auth/registration/', include('rest_auth.registration.urls')),
    re_path('account-confirm-email/', VerifyEmailView.as_view(), name='account_email_verification_sent'),
    re_path('account-confirm-email/<key>/', VerifyEmailView.as_view(), name='account_confirm_email'),

]

admin.site.site_header = _('Noruh')
admin.site.site_title = _('Noruh')

register/api/urls.py
from django.urls import path, include
from .views import (
    EstablishmentListAPIView,
    EstablishmentDetailAPIView,
    VerifyIfPromocodeIsEnabledView,
)
from .views import CuisineTypeListAPIView, MenuListAPIView
from .views import (
    BillAPIPost,
    BillHistoryAPIList,
    BillMemberAPIView,
    BillMemberAPICreate,
    BillMemberAPIConfirm,
    BillMemberAPIJoinCancel,
    BillMemberAPIConfirmAll,
    BillMemberAPIExitWithouPayment,
    OrderAPIUpdate,
    OrderAPIPost,
    OrderAPIDiscountPost,
    RequestAPIView,
    EvaluationAPIPost,
    EvaluationAPIView,
    EvaluationStatus,
)
from .views import (
    RegistrationUser,
    ForgotMyPasswordView,
    ResetPasswordUser,
    ProfileAPIUpdate,
    UserLoggedAPIList,
    UserAPIDetail,
    LogoutView,
)
from .views import (
    FacebookLogin,
    GoogleLogin,
)
from rest_auth.registration.views import (
    SocialAccountListView,
    SocialAccountDisconnectView
)


urlpatterns = [

    # Endpoints for Login, User and Registration
    path('user/registration/', RegistrationUser.as_view(), name='registration'),
    path('user/logout/', LogoutView.as_view(), name='logout'),
    path('user/forgot_password/', ForgotMyPasswordView.as_view(), name='forgot_password'),
    path('user/reset_password/', ResetPasswordUser.as_view(), name='reset_password'),

    path('rest-auth/facebook/', FacebookLogin.as_view(), name='fb_connect'),
    path('rest-auth/google/', GoogleLogin.as_view(), name='gl_connect'),
    path('rest-auth/socialaccounts/', SocialAccountListView.as_view(),
         name='social_account_list'),
    path('rest-auth/socialaccounts/<int:pk>/disconnect/',
         SocialAccountDisconnectView.as_view(),
         name='social_account_disconnect'),
    path('user/', UserLoggedAPIList.as_view(), name='api_user_list'),
    path('user/profile/update/', ProfileAPIUpdate.as_view(),
         name='api_profile_update'),

    # Endpoints for Cuisine Types, Establishment, Menu, Bill, Evaluations and Requests
    path('cuisine/list/', CuisineTypeListAPIView.as_view(),
         name='api_cuisine_type_list'),

    # List establishments for location and other search(promocode, opened, cuisine_type, featured, and name)
    path('establishment/list/', EstablishmentListAPIView.as_view(),
         name='api_establishment_list'),
    path('establishment/detail/<int:pk>/', EstablishmentDetailAPIView.as_view(),
         name='api_establishment_list_detail'),

    # List all items from menu use the `establishment_id` to path
    path('menu/list/<int:establishment_id>', MenuListAPIView.as_view(),
         name='api_menu_list'),

    # All endpoints for Bill and BillMemebers
    path('bill/history/', BillHistoryAPIList.as_view(),
         name='api_bill_history_list'),
    path('bill/active/', UserAPIDetail.as_view(),
         name='api_user_detail'),
    path('bill/create/', BillAPIPost.as_view(), name='api_bill_create'),
    path('bill/join/', BillMemberAPICreate.as_view(),
         name='api_bill_member_join'),
    path('bill/join/confirm/', BillMemberAPIConfirm.as_view(),
         name='api_bill_member_confirm'),
    path('bill/join/confirm/all/', BillMemberAPIConfirmAll.as_view(),
         name='api_bill_member_confirm_all'),
    path('bill/join/cancel/', BillMemberAPIJoinCancel.as_view(),
         name='api_bill_member_join_cancel'),
    path('bill/exit_without_payment/', BillMemberAPIExitWithouPayment.as_view(),
         name='api_bill_member_exit_bill'),
    path('bill/rating_status/', EvaluationStatus.as_view(),
         name='api_rating_status'),
    path('billmember/list/', BillMemberAPIView.as_view(),
         name='api_bill_member_list'),

    # Endpoints for create orders and update status from specific order
    path('order/post/', OrderAPIPost.as_view(), name='api_order_post'),
    path('order/offer/post/', OrderAPIDiscountPost.as_view(),
         name='api_order_post_offer'),
    path('order/update/<int:pk>/', OrderAPIUpdate.as_view(),
         name='api_order_update'),

    # Ednpoint for create a request attendance to Waiter
    path('request/post/', RequestAPIView.as_view(), name='api_request_post'),

    # Endpoints for create evaluation and list evaluations from establishment
    path('evaluation/post/', EvaluationAPIPost.as_view(),
         name='api_evaluation_post'),
    path('evaluation/list/<int:id_establishment>', EvaluationAPIView.as_view(),
         name='api_evaluation_list'),

    # Endpoint to verify if promocde is Enable or Disable
    path('promocode/status/', VerifyIfPromocodeIsEnabledView.as_view(),
         name='api_establishment_promocode_enabled'),

]

register/payment/urls.py
from django.urls import path

from .views import *

# Endpoints for Payments
urlpatterns = [
    path('create/app/', CreateAppAPIPost.as_view(), name='api_create_app'),
    path('create/wirecard_noruh/', CreateWirecardNoruhAPIPost.as_view(), name='api_create_wirecard_noruh'),

    path('list/customer/', ListCustomerAPIGet.as_view(), name='api_create_customer_post'),

    path('create/credit_card/', CreateCreditCardPost.as_view(), name='api_create_credit_card'),
    path('list/credit_card/', ListCreditCards.as_view(), name='api_list_credit_card'),
    path('delete/credit_card/<int:pk>', DeleteCreditCard.as_view(), name='api_delete_credit_card'),

    path('create/online/', CreatePaymentPostOnline.as_view(), name='api_create_payment_online'),
    path('create/offline/', CreatePaymentPostOffline.as_view(), name='api_create_payment_offline'),
    path('status/bill/<int:bill_id>', StatusBillPaymentApiView.as_view(), name='api_status_payment'),
    path('status/user/<int:user_id>', StatusUserPaymentApiView.as_view(), name='api_status_payment'),

]

register/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from .views import *

urlpatterns = [

     # Urls for authentication on noruh web

     path('change_password/', RecoverPasswordByApi.as_view(), name='change_password'),
     path('reset_passowrd/complete/', RecoverPasswordByApiComplete.as_view(), name='reset_password_complete'),

     path('login/', Login.as_view(), name='login'),
     path('user/logged/', ListUserLogged.as_view(), name='user_logged_detail'),
     path('user/logged/alter/<int:pk>/', AlterUser.as_view(), name='user_logged_alter'),

     path('', Home.as_view(), name='home'),
     path('terms_and_conditions/', TermsAndContions.as_view(), name='terms_and_conditions'),

     # Url's for Establishments and configurations
     path('establishment/create/', CreateEstablishment.as_view(),
          name='establishment_create'),
     path('establishment/list/all/', ListAllEstablishment.as_view(),
          name='establishment_list_all'),
     path('establishment/search/list/', ListSearchEstablishment.as_view(),
          name='establishment_search_list'),
     path('establishment/configurations/<int:id>/', ConfigurationsEstablishment.as_view(),
          name='establishment_configurations'),
     path('establishment/base/<int:id>/', BaseEstablishment.as_view(),
          name='establishment_base'),
     path('establishment/update/location/<int:pk>/', UpdateEstablismentLocation.as_view(),
          name='establishment_update_location'),
     path('establishment/update/description/<int:pk>/', UpdateEstablismentDescription.as_view(),
          name='establishment_update_description'),
     path('establishment/update/amenities/<int:pk>/', UpdateEstablismentAmenities.as_view(),
          name='establishment_update_amenities'),
     path('establishment/update/gps_restriction/<int:pk>/', UpdateGPSRestrictionEstablishment.as_view(),
          name='establishment_update_gps_restriction'),
     path('establishment/update/featured/<int:pk>/', UpdateFeaturedEstablishment.as_view(),
          name='establishment_update_featured'),
     path('establishment/update/enable/<int:pk>/', DisableEstablishment.as_view(),
         name='establishment_update_enable'),
     path('establishment/update/taxes/<int:pk>/', UpdateEstablismentTaxes.as_view(),
          name='establishment_update_taxes'),
     path('establishment/update/pays_payment_tax/<int:pk>/', UpdateEstablishmentPaysPaymentTax.as_view(),
          name='establishment_update_pays_payment_tax'),
     path('establishment/update/couvert/<int:pk>/', UpdateEstablismentCouvert.as_view(),
          name='establishment_update_couvert'),
     path('establishment/update/offer_range_value/<int:pk>/', UpdateEstablismentOfferRangeValue.as_view(),
          name='establishment_update_offer_range_value'),
     path('establishment/update/open_close/<int:pk>/', UpdateOpenOrCloseEstablishment.as_view(),
          name='establishment_update_open_close'),
     path('establishment/delete/<int:pk>/', DeleteEstablishment.as_view(),
          name='establishment_delete'),
     path('establishment/create/photo/<int:establishment_id>/', AddPhotoOnEstablishment.as_view(),
          name='establishment_add_photo'),
     path('establishment/photo/delete/<int:pk>/', DeletePhotoFromEstablishment.as_view(),
          name='establishment_delete_photo'),
     path('dashboard/', DashboardAllEstablishments.as_view(), name='dashboard_all_establishments'),
     path('establishment/dashboard/<int:establishment_id>/', DashboardEstablishment.as_view(),
          name='establishment_dashboard'),
     path('establishment/dashboard/items_more_requested/<int:establishment_id>/', ListAllItemsMoreRequested.as_view(),
          name='establishment_items_more_requested'),

     # Url's for when Request a Waiter
     path('establishment/requests/list/<int:establishment_id>/',
          RequestWaiter.as_view(), name='request_list'),
     path('establishment/requests/accept/<int:pk>/',
          AcceptRequestWaiter.as_view(), name='accept_request'),
     path('establishment/requests/accept/all/<int:establishment_id>/',
          AcceptAllRequestWaiter.as_view(), name='accept_all_requests'),

     # Url's for Establishment Evaluations
     path('establishment/evaluation/list/<int:establishment_id>/',
          ListEvaluation.as_view(), name='evaluation_list'),
     path('establishment/evaluation/answer/<int:evaluation_id>/',
          CreateAnswerToEvaluation.as_view(), name='answer_evaluation'),
     path('establishment/evaluation/delete/<int:pk>/',
          DeleteEvaluation.as_view(), name='evaluation_delete'),
     path('establishment/evaluation/answer/delete/<int:pk>/',
          DeleteAnswerEvaluation.as_view(), name='evaluation_answer_delete'),

     # Url's for Employees
     path('establishment/employee/create/', CreateEmployee.as_view(),
          name='employee_create'),
     path('establishment/employee/list/<int:establishment_id>/',
          ListEmployeeEstablishment.as_view(), name='employee_list_establishment'),
     path('establishment/employee/list/<int:establishment_id>/search/',
          ListSearchEmployeeEstablishment.as_view(), name='employee_list_search_establishment'),
     path('establishment/employee/list/', ListEmployeeAll.as_view(),
          name='employee_list_all'),
     path('establishment/employee/list/search/', ListSearchEmployee.as_view(),
          name='employee_search_list'),
     path('establishment/employee/detail/<int:pk>/',
          DetailEmployee.as_view(), name='employee_detail'),
     path('establishment/employee/alter/<int:pk>/',
          AlterEmployee.as_view(), name='employee_alter'),
     path('establishment/employee/delete/<int:pk>/',
          DeleteEmployee.as_view(), name='employee_delete'),

     # Url's for Menu, MenuItem, ItemCategory, Observation
     path('menu/list/<int:establishment_id>/', ListMenuFromEstablishment.as_view(),
          name='menu_list_from_establishment'),
     path('menu/list/<int:establishment_id>/search/', ListMenuSearchFromEstablishment.as_view(),
          name='menu_list_search_from_establishment'),

     # Items from Menu
     path('menu/add/item/<int:establishment_id>/',
          CreateItemOnMenu.as_view(), name='menu_create_item'),
     path('menu/list/item/<int:establishment_id>/',
          ListMenuItems.as_view(), name='menu_item_list'),
     path('menu/list/item/<int:establishment_id>/search/',
          ListMenuItemsSearch.as_view(), name='menu_item_list_search'),
     path('menu/list/item/update/<int:pk>/',
          UpdateItemOnMenu.as_view(), name='menu_item_update'),
     path('menu/list/item/delete/<int:pk>/',
          DeleteItemOnMenu.as_view(), name='menu_item_delete'),

     # Category from Menu
     path('menu/category/create/<int:establishment_id>/',
          CreateCategory.as_view(), name='menu_category_create'),
     path('menu/category/list/<int:establishment_id>/',
          ListCategory.as_view(), name='menu_category_list'),
     path('menu/category/update/<int:pk>/',
          UpdateCategory.as_view(), name='menu_category_update'),
     path('menu/category/delete<int:pk>/',
          DeleteCategory.as_view(), name='menu_category_delete'),

     # Observations from Menu
     path('menu/observation/create/<int:establishment_id>',
          CreateObservationItem.as_view(), name='menu_observation_item_create'),
     path('menu/observation/list/<int:establishment_id>/',
          ListObservationItem.as_view(), name='menu_observation_list'),
     path('menu/observation/update/<int:pk>/',
          UpdateObservationItem.as_view(), name='menu_observation_update'),
     path('menu/observation/delete/<int:pk>/',
          DeleteObservationItem.as_view(), name='menu_observation_delete'),

     # Menu Offers
     path('menu/offer/create/<int:establishment_id>',
          CreateMenuOffer.as_view(), name='menu_offer_create'),
     path('menu/offer/list/<int:establishment_id>/',
          ListMenuOffers.as_view(), name='menu_offer_list'),
     path('menu/offer/delete/<int:pk>/',
          DeleteMenuOffer.as_view(), name='menu_offer_delete'),
     path('menu/offer/update/<int:pk>/',
          UpdateMenuOffer.as_view(), name='menu_offer_update'),

     # Url's for Orders, Bills and Tables
     path('orders/list/<int:establishment_id>/',
          ListOrders.as_view(), name='orders_list'),
     path('orders/list/kitchen/pending/<int:establishment_id>/',
          ListOrdersPendingKitchen.as_view(), name='orders_list_kitchen_pending'),
     path('orders/list/kitchen/preparing/<int:establishment_id>/',
          ListOrdersPreparingKitchen.as_view(), name='orders_list_kitchen_preparing'),
     path('orders/list/kitchen/done/<int:establishment_id>/',
          ListOrdersDoneKitchen.as_view(), name='orders_list_kitchen_done'),

     # Cancel Orders Button
     path('order/cancel_from_list_orders/<int:order_id>/',
          CancelOrderOnListOrders.as_view(), name='order_cancel_button_on_list_orders'),
     path('order/cancel_from_bill/<int:order_id>/',
          CancelOrderOnListBill.as_view(), name='order_cancel_button_on_list_bills'),

     # Url's for Views for Kitchen List Orders
     path('orders/list/kitchen/done/<int:establishment_id>/search/user/',
          ListSearchDoneOrdersByUsers.as_view(), name='orders_kitchen_done_search_user'),
     path('orders/list/kitchen/done/<int:establishment_id>/search/table/',
          ListFilterOrdersByTableDone.as_view(), name='orders_kitchen_done_search_table'),
     path('orders/list/<int:establishment_id>/search/',
          ListSearchOrders.as_view(), name='orders_search_list'),
     path('orders/list/filter/category/<int:establishment_id>/search/',
          KitchenFilterOrdersByCategory.as_view(), name='orders_kitchen_category_filter'),
     path('orders/list/<int:establishment_id>/filter_by_table/',
          ListFilterOrdersByTable.as_view(), name='orders_filter_by_table'),

register/templates/components/establishment/establishment_component_amenities.html
{% extends 'components/establishment/establishment_component_base.html' %}
{% load static %}

{% block title %}Comodidades{% endblock %}

{% block buttons %}
<a id="card-amenities" href="{% url 'register:establishment_update_amenities' establishment.pk %}"> Editar </a>
{% endblock buttons %}

{% block content %}
{% for amenity in amenities %}
<label class="label is-size-6 has-text-weight-normal has-text-secondary amenities-control"> <i
    class="amenities {{ amenity.name }}-no-color"></i> {{ amenity.name }}</label>
{% endfor %}

<div class="modal table_item">
  <div class="modal-background"></div>
  <div class="modal-content"></div>
  <button class="modal-close is-large" aria-label="close"></button>
</div>

<script>
  $("a#card-amenities").click(function (e) {
    e.stopImmediatePropagation(); // those pesky handlers
    e.preventDefault();
    url = this.href;

    $.get(url, function () {
      console.log("Fetching data");
    })
      .done(function (data) {
        console.log("Data fetched succesfully :)");
        $(".modal.table_item > .modal-content").html(data);
        $(".modal.table_item").addClass("is-active");
        $(".modal .modal-content button.is-danger").click(function () {
          $(".modal").removeClass("is-active");
        });
      })
      .fail(function (xhr) {
        console.log("Error: ", xhr);
      });

    $(".modal-close, .modal-background").click(function () {
      $(".modal").removeClass("is-active");
    });
  });
</script>


{% endblock content %}

register/templates/components/establishment/establishment_component_base.html
<div class="columns is-multiline has-magt-2">
    <div class="card column is-full has-pad-3">
        <div class="level is-border-bottom has-padb-2">
            <div class="level-left">
                <div class="level-item">
                    <label for=""
                        class="label is-size-5 has-text-weight-normal has-text-primary">{% block title %}{% endblock %}</label>
                </div>
            </div>
            <div class="level-right">
                <div class="level-item">
                    {% block base_buttons %}
                        <button id="activate_obs" class="button is-link is-outlined">
                            {% block buttons %}{% endblock buttons %}
                        </button>
                    {% endblock %}
                </div>
            </div>
        </div>

        {% block content %}
        {% endblock content %}

    </div>
</div>

register/templates/components/establishment/establishment_component_description.html
<div class="columns is-multiline has-magt-2">
    <div class="card column is-full">
        <div class="media">
            <div class="media-left">
                <img class="restaurant-card__avatar is-120" src="{{ establishment.logo_url.url }}">
            </div>

            <div class="media-content has-pad-3">
                <label class="label is-size-5 has-text-weight-normal has-text-primary">Nome</label>
                <p class="is-border-bottom as-pickup">{{ establishment.name }}</p>

                <label for="" class="label is-size-5 has-text-weight-normal has-text-primary">
                    Tipo de Cozinha
                </label>

                <p class="is-border-bottom as-pickup">{{ establishment.cuisine_type }}</p>
            </div>

            <div class="media-right has-magt-2 has-magr-2">
                <button id="activate_obs" class="button is-link is-outlined">
                    <a id="card-description"
                        href="{% url 'register:establishment_update_description' establishment.pk %}"> Editar </a>
                </button>
            </div>
        </div>
        <div class="column is-full has-padl-4 has-padr-4">
            <label for="" class="label is-size-5 has-text-weight-normal has-text-primary">Descrição</label>
            <p class="is-border-top as-pickup">{{ establishment.description }}</p>
        </div>
    </div>
</div>


<div class="modal table_item">
    <div class="modal-background"></div>
    <div class="modal-content"></div>
    <button class="modal-close is-large" aria-label="close"></button>
</div>

{% block extra-js %}
<script>
    $("a#card-description").click(function (e) {
        e.stopImmediatePropagation(); // those pesky handlers
        e.preventDefault();
        url = this.href;

        $.get(url, function () {
            console.log("Fetching data");
        })
            .done(function (data) {
                console.log("Data fetched succesfully :)");
                $(".modal.table_item > .modal-content").html(data);
                $(".modal.table_item").addClass("is-active");
                $(".modal .modal-content button.is-danger").click(function () {
                    $(".modal").removeClass("is-active");
                });
            })
            .fail(function (xhr) {
                console.log("Error: ", xhr);
            });

        $(".modal-close, .modal-background").click(function () {
            $(".modal").removeClass("is-active");
        });
    });
</script>
{% endblock %}

register/templates/components/establishment/establishment_component_rates.html
{% extends 'components/establishment/establishment_component_base_rate.html' %}

{% block title %}Taxas do Estabelecimento{% endblock %}


{% block buttons %}
<button id="activate_obs" class="button is-link is-outlined">
    <a id="card-offer-range-value" href="{% url 'register:establishment_update_offer_range_value' establishment.pk %}"> Editar Intervalo de Valor para Ofertas </a>
</button>
<button id="activate_obs" class="button is-link is-outlined">
    <a id="card-couvert" href="{% url 'register:establishment_update_couvert' establishment.pk %}"> Editar Couvert </a>
</button>
{% if user.is_superuser %}
<button id="activate_cat" class="button is-link is-outlined">
    <a href="{% url 'register:establishment_update_taxes' establishment.pk %}"> Editar Taxas </a>
</button>
{% endif %}
{% endblock buttons %}


{% block content %}

<div class="level is-bg-tertiary has-pad-2 has-magb-2">
    <div class="level-left">
        <div class="level-item">
            <label for="" class="label is-size-6 has-text-weight-normal has-text-tertiary">Taxa</label>
        </div>
    </div>
    <div class="level-right">
        <div class="level-item">
            <label for="" class="label is-size-6 has-text-weight-normal has-text-tertiary">Valor</label>
        </div>
    </div>
</div>

<div class="level is-border-bottom has-padb-2">
    <div class="level-left">
        <label for="" class="label is-size-6 has-text-weight-normal has-text-tertiary">Couvert Artistico:</label>
    </div>
    <div class="level-right">
        <label for="" class="label is-size-6 has-text-weight-normal has-text-tertiary">R${{establishment.taxe_couvert}}</label>
    </div>
</div>


<p> </p>
{% if user.is_superuser %}

<div class="level is-border-bottom-c has-padb-2">
    <div class="level-left">
        <label for="" class="label is-size-6 has-text-weight-normal has-text-tertiary">Taxa Noruh:</label>
    </div>
    <div class="level-right">
        <label for="" class="label is-size-6 has-text-weight-normal has-text-tertiary">R${{establishment.noruh_fee}}</label>
    </div>
</div>

<div class="level is-border-bottom-c has-padb-2">
    <div class="level-left">
        <label for="" class="label is-size-6 has-text-weight-normal has-text-tertiary">Taxa Fixa do Moip:</label>
    </div>
    <div class="level-right">
        <label for="" class="label is-size-6 has-text-weight-normal has-text-tertiary">R${{establishment.moip_fee}}</label>
    </div>
</div>

<div class="level is-border-bottom-c has-padb-2">
    <div class="level-left">
        <label for="" class="label is-size-6 has-text-weight-normal has-text-tertiary">Porcentagem do Moip:</label>
    </div>
    <div class="level-right">
        <label for="" class="label is-size-6 has-text-weight-normal has-text-tertiary">{{establishment_payment_tax}}%</label>
    </div>
</div>

<div class="level is-border-bottom-c has-padb-2">
    <div class="level-left">
        <label for="" class="label is-size-6 has-text-weight-normal has-text-tertiary">Valor para Intervalo de Ofertas:</label>
    </div>
    <div class="level-right">
        <label for="" class="label is-size-6 has-text-weight-normal has-text-tertiary">R${{establishment.offer_range_value}}</label>
    </div>
</div>

<div class="level is-border-bottom-c has-padb-2">
    <div class="level-left">
        <label for="" class="label is-size-6 has-text-weight-normal has-text-tertiary">Porcentagem para repasse offline:</label>
    </div>
    <div class="level-right">
        <label for="" class="label is-size-6 has-text-weight-normal has-text-tertiary">{{establishment_offline_percentage}}%</label>
    </div>
</div>

<div class="level is-border-bottom-c has-padb-2">
    <div class="level-left"> Pagar Taxas do Moip</div>
    <div class="level-item has-text-centered">

    </div>
    <div class="level-right">
        <div class="onoffswitch">
            <input type="checkbox" checkbox="true" name="onoffswitch" class="onoffswitch-checkbox"
                id="update_pay_moip">
            <label class="onoffswitch-label" for="update_pay_moip"></label>
        </div>
    </div>
</div>



{% endif %}


<div class="modal table_item">
    <div class="modal-background"></div>
    <div class="modal-content"></div>
    <button class="modal-close is-large" aria-label="close"></button>
</div>

<script>
    {% if establishment.pays_payment_tax %}
    $("#update_pay_text").each(function () { this.innerText = "Ativo"; });
    $("#update_pay_moip").each(function () { this.checked = true; });
    {% elif not establishment.pays_payment_tax %}
    $("#update_pay_text").each(function () { this.innerText = "Inativo"; });
    $("#update_pay_moip").each(function () { this.checked = false; });
    {% else %}
    {% endif %}

    $("#update_pay_moip").click(function (e) {
        $.ajax({
            url: "{% url 'register:establishment_update_pays_payment_tax' establishment.pk %}",
            method: "GET"
        })
            .done(function (data) {
                if (data.opened) {
                    $("#update_pay_text").each(function () { this.innerText = "Ativo"; });
                    $("#update_pay_moip").each(function () { this.checked = true; });
                } else {
                    $("#update_pay_text").each(function () { this.innerText = "Inativo"; });
                }
            })
            .fail(function (xhr) {
                console.log('error', xhr);
            });
        e.stopImmediatePropagation();
    });

    $("a#card-couvert").click(function (e) {
        e.stopImmediatePropagation(); // those pesky handlers
        e.preventDefault();
        url = this.href;

        $.get(url, function () {
            console.log("Fetching data");
        })
            .done(function (data) {
                console.log("Data fetched succesfully :)");
                $(".modal.table_item > .modal-content").html(data);
                $(".modal.table_item").addClass("is-active");
                $(".modal .modal-content button.is-danger").click(function () {
                    $(".modal").removeClass("is-active");
                });
            })
            .fail(function (xhr) {
                console.log("Error: ", xhr);
            });

        $(".modal-close, .modal-background").click(function () {
            $(".modal").removeClass("is-active");
        });
    });

    $("a#card-offer-range-value").click(function (e) {
        e.stopImmediatePropagation(); // those pesky handlers
        e.preventDefault();
        url = this.href;

        $.get(url, function () {
            console.log("Fetching data");
        })
            .done(function (data) {
                console.log("Data fetched succesfully :)");
                $(".modal.table_item > .modal-content").html(data);
                $(".modal.table_item").addClass("is-active");
                $(".modal .modal-content button.is-danger").click(function () {
                    $(".modal").removeClass("is-active");
                });
            })
            .fail(function (xhr) {
                console.log("Error: ", xhr);
            });

        $(".modal-close, .modal-background").click(function () {
            $(".modal").removeClass("is-active");
        });
    });
</script>


{% endblock content %}