noruh_backend/urls.py
from django.utils.translation import gettext as _
from django.contrib import admin
from django.urls import path, re_path, include

from rest_framework.documentation import include_docs_urls
from rest_auth.registration.views import VerifyEmailView

urlpatterns = [
    path('', include(('register.urls', 'register'), namespace='register')),
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),

    path('api/auth/', include('rest_framework_social_oauth2.urls')),

    path('api/', include(('register.api.urls', 'register-api'), namespace='register-api')),
    path('api/docs/', include_docs_urls(title='Noruh API Documentation')),
    path('api/payment/', include(('register.payment.urls', 'register-api-payment'), namespace='register-api-payment')),
    path('api/rest-auth/', include('rest_auth.urls')),
    path('api/rest-auth/accounts/', include('allauth.urls'), name='socialaccount_signup'),
    path('api/rest-auth/registration/', include('rest_auth.registration.urls')),
    re_path('account-confirm-email/', VerifyEmailView.as_view(), name='account_email_verification_sent'),
    re_path('account-confirm-email/<key>/', VerifyEmailView.as_view(), name='account_confirm_email'),

]

admin.site.site_header = _('Noruh')
admin.site.site_title = _('Noruh')

register/api/urls.py
from django.urls import path, include
from .views import (
    EstablishmentListAPIView,
    EstablishmentDetailAPIView,
    VerifyIfPromocodeIsEnabledView,
)
from .views import CuisineTypeListAPIView, MenuListAPIView
from .views import (
    BillAPIPost,
    BillHistoryAPIList,
    BillMemberAPIView,
    BillMemberAPICreate,
    BillMemberAPIConfirm,
    BillMemberAPIJoinCancel,
    BillMemberAPIConfirmAll,
    BillMemberAPIExitWithouPayment,
    OrderAPIUpdate,
    OrderAPIPost,
    OrderAPIDiscountPost,
    RequestAPIView,
    EvaluationAPIPost,
    EvaluationAPIView,
    EvaluationStatus,
)
from .views import (
    RegistrationUser,
    ForgotMyPasswordView,
    ResetPasswordUser,
    ProfileAPIUpdate,
    UserLoggedAPIList,
    UserAPIDetail,
    LogoutView,
)
from .views import (
    FacebookLogin,
    GoogleLogin,
)
from rest_auth.registration.views import (
    SocialAccountListView,
    SocialAccountDisconnectView
)


urlpatterns = [

    # Endpoints for Login, User and Registration
    path('user/registration/', RegistrationUser.as_view(), name='registration'),
    path('user/logout/', LogoutView.as_view(), name='logout'),
    path('user/forgot_password/', ForgotMyPasswordView.as_view(), name='forgot_password'),
    path('user/reset_password/', ResetPasswordUser.as_view(), name='reset_password'),

    path('rest-auth/facebook/', FacebookLogin.as_view(), name='fb_connect'),
    path('rest-auth/google/', GoogleLogin.as_view(), name='gl_connect'),
    path('rest-auth/socialaccounts/', SocialAccountListView.as_view(),
         name='social_account_list'),
    path('rest-auth/socialaccounts/<int:pk>/disconnect/',
         SocialAccountDisconnectView.as_view(),
         name='social_account_disconnect'),
    path('user/', UserLoggedAPIList.as_view(), name='api_user_list'),
    path('user/profile/update/', ProfileAPIUpdate.as_view(),
         name='api_profile_update'),

    # Endpoints for Cuisine Types, Establishment, Menu, Bill, Evaluations and Requests
    path('cuisine/list/', CuisineTypeListAPIView.as_view(),
         name='api_cuisine_type_list'),

    # List establishments for location and other search(promocode, opened, cuisine_type, featured, and name)
    path('establishment/list/', EstablishmentListAPIView.as_view(),
         name='api_establishment_list'),
    path('establishment/detail/<int:pk>/', EstablishmentDetailAPIView.as_view(),
         name='api_establishment_list_detail'),

    # List all items from menu use the `establishment_id` to path
    path('menu/list/<int:establishment_id>', MenuListAPIView.as_view(),
         name='api_menu_list'),

    # All endpoints for Bill and BillMemebers
    path('bill/history/', BillHistoryAPIList.as_view(),
         name='api_bill_history_list'),
    path('bill/active/', UserAPIDetail.as_view(),
         name='api_user_detail'),
    path('bill/create/', BillAPIPost.as_view(), name='api_bill_create'),
    path('bill/join/', BillMemberAPICreate.as_view(),
         name='api_bill_member_join'),
    path('bill/join/confirm/', BillMemberAPIConfirm.as_view(),
         name='api_bill_member_confirm'),
    path('bill/join/confirm/all/', BillMemberAPIConfirmAll.as_view(),
         name='api_bill_member_confirm_all'),
    path('bill/join/cancel/', BillMemberAPIJoinCancel.as_view(),
         name='api_bill_member_join_cancel'),
    path('bill/exit_without_payment/', BillMemberAPIExitWithouPayment.as_view(),
         name='api_bill_member_exit_bill'),
    path('bill/rating_status/', EvaluationStatus.as_view(),
         name='api_rating_status'),
    path('billmember/list/', BillMemberAPIView.as_view(),
         name='api_bill_member_list'),

    # Endpoints for create orders and update status from specific order
    path('order/post/', OrderAPIPost.as_view(), name='api_order_post'),
    path('order/offer/post/', OrderAPIDiscountPost.as_view(),
         name='api_order_post_offer'),
    path('order/update/<int:pk>/', OrderAPIUpdate.as_view(),
         name='api_order_update'),

    # Ednpoint for create a request attendance to Waiter
    path('request/post/', RequestAPIView.as_view(), name='api_request_post'),

    # Endpoints for create evaluation and list evaluations from establishment
    path('evaluation/post/', EvaluationAPIPost.as_view(),
         name='api_evaluation_post'),
    path('evaluation/list/<int:id_establishment>', EvaluationAPIView.as_view(),
         name='api_evaluation_list'),

    # Endpoint to verify if promocde is Enable or Disable
    path('promocode/status/', VerifyIfPromocodeIsEnabledView.as_view(),
         name='api_establishment_promocode_enabled'),

]

register/payment/urls.py
from django.urls import path

from .views import *

# Endpoints for Payments
urlpatterns = [
    path('create/app/', CreateAppAPIPost.as_view(), name='api_create_app'),
    path('create/wirecard_noruh/', CreateWirecardNoruhAPIPost.as_view(), name='api_create_wirecard_noruh'),

    path('list/customer/', ListCustomerAPIGet.as_view(), name='api_create_customer_post'),

    path('create/credit_card/', CreateCreditCardPost.as_view(), name='api_create_credit_card'),
    path('list/credit_card/', ListCreditCards.as_view(), name='api_list_credit_card'),
    path('delete/credit_card/<int:pk>', DeleteCreditCard.as_view(), name='api_delete_credit_card'),

    path('create/online/', CreatePaymentPostOnline.as_view(), name='api_create_payment_online'),
    path('create/offline/', CreatePaymentPostOffline.as_view(), name='api_create_payment_offline'),
    path('status/bill/<int:bill_id>', StatusBillPaymentApiView.as_view(), name='api_status_payment'),
    path('status/user/<int:user_id>', StatusUserPaymentApiView.as_view(), name='api_status_payment'),

]

register/urls.py
     path('establishment/employee/list/<int:establishment_id>/search/',
          ListSearchEmployeeEstablishment.as_view(), name='employee_list_search_establishment'),
     path('establishment/employee/list/', ListEmployeeAll.as_view(),
          name='employee_list_all'),
     path('establishment/employee/list/search/', ListSearchEmployee.as_view(),
          name='employee_search_list'),
     path('establishment/employee/detail/<int:pk>/',
          DetailEmployee.as_view(), name='employee_detail'),
     path('establishment/employee/alter/<int:pk>/',
          AlterEmployee.as_view(), name='employee_alter'),
     path('establishment/employee/delete/<int:pk>/',
          DeleteEmployee.as_view(), name='employee_delete'),

     # Url's for Menu, MenuItem, ItemCategory, Observation
     path('menu/list/<int:establishment_id>/', ListMenuFromEstablishment.as_view(),
          name='menu_list_from_establishment'),
     path('menu/list/<int:establishment_id>/search/', ListMenuSearchFromEstablishment.as_view(),
          name='menu_list_search_from_establishment'),

     # Items from Menu
     path('menu/add/item/<int:establishment_id>/',
          CreateItemOnMenu.as_view(), name='menu_create_item'),
     path('menu/list/item/<int:establishment_id>/',
          ListMenuItems.as_view(), name='menu_item_list'),
     path('menu/list/item/<int:establishment_id>/search/',
          ListMenuItemsSearch.as_view(), name='menu_item_list_search'),
     path('menu/list/item/update/<int:pk>/',
          UpdateItemOnMenu.as_view(), name='menu_item_update'),
     path('menu/list/item/delete/<int:pk>/',
          DeleteItemOnMenu.as_view(), name='menu_item_delete'),

     # Category from Menu
     path('menu/category/create/<int:establishment_id>/',
          CreateCategory.as_view(), name='menu_category_create'),
     path('menu/category/list/<int:establishment_id>/',
          ListCategory.as_view(), name='menu_category_list'),
     path('menu/category/update/<int:pk>/',
          UpdateCategory.as_view(), name='menu_category_update'),
     path('menu/category/delete<int:pk>/',
          DeleteCategory.as_view(), name='menu_category_delete'),

     # Observations from Menu
     path('menu/observation/create/<int:establishment_id>',
          CreateObservationItem.as_view(), name='menu_observation_item_create'),
     path('menu/observation/list/<int:establishment_id>/',
          ListObservationItem.as_view(), name='menu_observation_list'),
     path('menu/observation/update/<int:pk>/',
          UpdateObservationItem.as_view(), name='menu_observation_update'),
     path('menu/observation/delete/<int:pk>/',
          DeleteObservationItem.as_view(), name='menu_observation_delete'),

     # Menu Offers
     path('menu/offer/create/<int:establishment_id>',
          CreateMenuOffer.as_view(), name='menu_offer_create'),
     path('menu/offer/list/<int:establishment_id>/',
          ListMenuOffers.as_view(), name='menu_offer_list'),
     path('menu/offer/delete/<int:pk>/',
          DeleteMenuOffer.as_view(), name='menu_offer_delete'),
     path('menu/offer/update/<int:pk>/',
          UpdateMenuOffer.as_view(), name='menu_offer_update'),

     # Url's for Orders, Bills and Tables
     path('orders/list/<int:establishment_id>/',
          ListOrders.as_view(), name='orders_list'),
     path('orders/list/kitchen/pending/<int:establishment_id>/',
          ListOrdersPendingKitchen.as_view(), name='orders_list_kitchen_pending'),
     path('orders/list/kitchen/preparing/<int:establishment_id>/',
          ListOrdersPreparingKitchen.as_view(), name='orders_list_kitchen_preparing'),
     path('orders/list/kitchen/done/<int:establishment_id>/',
          ListOrdersDoneKitchen.as_view(), name='orders_list_kitchen_done'),

     # Cancel Orders Button
     path('order/cancel_from_list_orders/<int:order_id>/',
          CancelOrderOnListOrders.as_view(), name='order_cancel_button_on_list_orders'),
     path('order/cancel_from_bill/<int:order_id>/',
          CancelOrderOnListBill.as_view(), name='order_cancel_button_on_list_bills'),

     # Url's for Views for Kitchen List Orders
     path('orders/list/kitchen/done/<int:establishment_id>/search/user/',
          ListSearchDoneOrdersByUsers.as_view(), name='orders_kitchen_done_search_user'),
     path('orders/list/kitchen/done/<int:establishment_id>/search/table/',
          ListFilterOrdersByTableDone.as_view(), name='orders_kitchen_done_search_table'),
     path('orders/list/<int:establishment_id>/search/',
          ListSearchOrders.as_view(), name='orders_search_list'),
     path('orders/list/filter/category/<int:establishment_id>/search/',
          KitchenFilterOrdersByCategory.as_view(), name='orders_kitchen_category_filter'),
     path('orders/list/<int:establishment_id>/filter_by_table/',
          ListFilterOrdersByTable.as_view(), name='orders_filter_by_table'),
     path('orders/list/items/to/order/<int:establishment_id>/',
          ListItemsToOrder.as_view(), name='list_items_to_order'),
     path('orders/create/<int:establishment_id>/',
          CreateOrder.as_view(), name='order_create'),
     path('orders/update/<int:pk>/',
          UpdateOrder.as_view(), name='orders_update'),
     path('orders/kitchen_accepted_at/<int:order_id>/',
          KitchenAcceptOrder.as_view(), name='order_kitchen_accepted_at'),
     path('orders/kitchen_done_order/<int:order_id>/',
          KitchenDoneOrder.as_view(), name='order_kitchen_done'),
     path('orders/kitchen_cancel_order/<int:order_id>/',
          KitchenCancelOrder.as_view(), name='order_kitchen_cancel'),

     # Url's for Bills and BillPayment
     path('bill/list/<int:establishment_id>/',
          ListBillsOpened.as_view(), name='bill_list'),
     path('bill/list/closed/<int:establishment_id>/',
          ListBillsClosed.as_view(), name='bill_list_closed'),
     path('bill/list/<int:establishment_id>/search/',
          ListSearchBills.as_view(), name='bill_search_list'),
     path('bill/list/search/closed/<int:establishment_id>/search/',
          ListSearchBillsClosed.as_view(), name='bill_search_list_closed'),
     path('bill/payment/create/<int:bill_id>/',
          CreatePaymentAllBill.as_view(), name='bill_payment_create'),
     path('bill/payment/create/bill_member/<int:bill_member_id>/',
          CreatePaymentOnBillMember.as_view(), name='bill_member_payment_create'),
     path('bill/payment/aprove_or_reject/<int:bill_payment_id>/',
          ApproveOrRejectPayment.as_view(), name='bill_payment_aprove_or_reject'),
     path('bill/payment/reject/<int:bill_payment_id>/',
          RejectPayment.as_view(), name='bill_payment_reject'),
     path('bill/bill_members/list/<int:bill_id>/',
          ListBillMembersOnBill.as_view(), name='bill_member_on_bill_list'),
     path('ajax/load_bill_members/', 
          LoadBillMembers.as_view(), name='ajax_load_bill_members'),          
     path('bill/orders/list/<int:bill_id>/',
          ListOrdersFromBill.as_view(), name='orders_from_bill'),

     # Url's for Tables and TableZone
     path('table_zone/create/<int:establishment_id>/',
          CreateTableZone.as_view(), name='table_zone_create'),
     path('table_zone/list/<int:establishment_id>/',
          ListTableZone.as_view(), name='table_zone_list'),
     path('table_zone/update/<int:pk>/',
          UpdateTableZone.as_view(), name='table_zone_update'),
     path('table_zone/delete/<int:pk>/',
          DeleteTableZone.as_view(), name='table_zone_delete'),
     path('table_zone/update/active_or_desactive/<int:pk>/',
          DesactiveTableZone.as_view(), name='table_zone_active_or_desactive'),
     path('table/create/<int:table_zone_id>/<int:establishment_id>/',
          CreateTable.as_view(), name='table_create'),
     path('table/update/<int:pk>/', UpdateTable.as_view(), name='table_update'),
     path('table/update/enabled/<int:pk>/',
          UpdateTableEnableOrDesable.as_view(), name='table_update_enabled'),
     path('table/delete/<int:pk>/', DeleteTable.as_view(), name='table_delete'),

     # Url's for Operating Hours
     path('operating_hours/create/<int:establishment_id>/',
          CreateOperatingHours.as_view(), name='operating_hour_create'),
     path('operating_hours/delete/<int:pk>/',
          DeleteOperatingHour.as_view(), name='operating_hour_delete'),

     # Url's for Promocodes
     path('promocode/create/<int:establishment_id>/',
          CreatePromoCode.as_view(), name='promocode_create'),
     path('promocode/update/<int:pk>/',
          UpdatePromoCodes.as_view(), name='promocode_update'),
     path('promocode/delete/<int:pk>/',
          DeletePromocodes.as_view(), name='promocode_delete'),

     # Url's for Events
     path('events/create/<int:establishment_id>/',
          CreateEvents.as_view(), name='events_create'),
     path('events/update/<int:pk>/',
          UpdateEvents.as_view(), name='events_update'),
     path('events/delete/<int:pk>/',
          DeleteEvents.as_view(), name='events_delete'),

     # Url's for Wirecard Payment
     path('wirecard/create/<int:establishment_id>/',
          CreateWirecard.as_view(), name='wirecard_create'),
     path('wirecard/company/create/<int:establishment_id>/',
          CreateCompanyWirecard.as_view(), name='wirecard_company_create'),          
     path('wirecard/detail/<int:pk>/',
          DetailWirecard.as_view(), name='wirecard_detail'),

     # Url's for offline Compensations
     path('offline/compensations/', ListCompensations.as_view(),
          name='offline_compensations'),
     path('offline/compensations/check_month/<int:month>/<int:year>/<int:establishment_id>/',
          CreateCompensation.as_view(), name='offline_compensations_check_month'),    
     path('offline/compensations/generate_report/<int:month>/<int:year>/<int:establishment_id>/', GenerateCSVReport.as_view(),
          name='offline_compensations_generate_report'),
           
]

if settings.DEBUG:

register/templates/components/kitchen/navigation_in_kitchen.html
<div class="container">
    <div class="column has-mag-3-left">
        <div class="tabs">
            <ul>
                <li {% if request.resolver_match.url_name == "orders_list_kitchen_pending" %} 
                        class="is-active"
                    {% endif %}
                    {% if request.resolver_match.url_name == "orders_kitchen_category_filter" %} 
                        class="is-active"
                    {% endif %}>
                    <a href="{% url 'register:orders_list_kitchen_pending' establishment.pk %}">Pendentes</a>
                </li>

                <li {% if request.resolver_match.url_name == "orders_list_kitchen_preparing" %} 
                        class="is-active"
                    {% endif %}>
                    <a href="{% url 'register:orders_list_kitchen_preparing' establishment.pk %}">Preparando</a>
                </li>
                
                <li {% if request.resolver_match.url_name == "orders_list_kitchen_done" %} 
                        class="is-active"
                    {% endif %}>
                    <a href="{% url 'register:orders_list_kitchen_done' establishment.pk %}"> Pronto</a>
                </li>
            </ul>
        </div>
    </div>
</div>

register/templates/components/kitchen/order_list.html
{% extends 'establishment_base.html' %}

{% load load_permissions %}

{% block title %}Pedidos{% endblock %}

{% block content %}
<div class="columns">
    <div class="column is-10 is-offset-1">
        <div class="columns is-multiline">
            {% if not request.user.is_superuser %}
            <div class="column is-full">
                <h1 class="is-title is-size-3 has-text-primary">Pedidos</h1>
            </div>
            {% endif %}
            <div class="column is-full">
                <div class="level">
                    <div class="level-left">
                        <form action="{% url 'register:orders_filter_by_table' establishment.id %}" id="searchform">
                            <div class="field is-horizontal">
                                <div class="level-item">
                                    <p class="is-size-6">Filtrar por mesa:</p>
                                </div>
                                <div class="field-body">
                                    <div class="field">
                                        <div class="level-item">
                                            <div class="select">
                                                <select name="table">
                                                    <option></option>
                                                    {% for table in tables %}
                                                        <option value={{table.id}}>
                                                        {% if table.name == 'order_remote' %}
                                                            Retirar no Balcao
                                                        {% else %}
                                                            {{ table.name }}
                                                        {% endif %}                                           
                                                        </option>
                                                    {% endfor %}
                                                </select>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="field">
                                        <div class="level-item">
                                            <div class="field has-addons">
                                                <p class="control has-icons-left">
                                                    <input type="search" class="input"
                                                        placeholder="Busque pelo nome do usuario" name="first_name">
                                                    <span class="icon is-small is-left">
                                                        <i class="fas fa-search"></i>
                                                    </span>
                                                </p>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </form>
                    </div>
                    <div class="level-right">
                        <div class="level-item">
                            {% if request.resolver_match.url_name == "orders_filter_by_table" %}
                            <a class="button" href="{% url 'register:orders_list' establishment.id %}">Remover
                                Filtro</a>
                            {% endif %}
                        </div>
                        <div class="level-item">
                            <a class="button is-link" id="activate_item"
                                onclick="createOrder('{% url 'register:order_create' establishment.id %}')">Fazer
                                Pedido</a>
                        </div>
                    </div>
                </div>
            </div>
            <div class="column is-full">
                <div class="box">
                    <h3 class="subtitle is-5 has-text-primary">Pedidos</h3>
                    <table class="table is-fullwidth">
                        <thead>
                            <th>Numero do Pedido</th>
                            <th>Qtd</th>
                            <th>Item</th>
                            <th>Mesa</th>
                            <th>Usuario</th>
                            <th>Status</th>
                            <th></th>
                        </thead>
                        <tbody>
                            {% for item in all_items %}
                            <tr>
                                <td>#{{item.id}}</td>
                                <td>{{item.quantity}}</td>
                                <td>{{item.item.name}}</td>
                                <td>
                                    {% if item.bill.table.name == 'order_remote' %}
                                        Retirar no Balcao
                                    {% else %}
                                        {{ item.bill.table }}
                                    {% endif %}                                           
                                </td>
                                <td>{{item.user.first_name}}</td>
                                <td>
                                    {% if item.status == item.STATUS_PENDING %}
                                    <span class="tag is-normal is-rounded is-light">Aguardando</span>
                                    {% elif item.status == item.STATUS_DONE %}
                                    <span class="tag is-normal is-success is-rounded">Pronto</span>
                                    {% elif item.status == item.STATUS_PREPARING %}
                                    <span class="tag is-normal is-warning is-rounded">Preparando</span>
                                    {% elif item.status == item.STATUS_REJECTED %}
                                    <span class="tag is-normal is-danger is-rounded">Cancelado</span>
                                    {% endif %}
                                </td>
                                <td>
                                    {% if item.status == item.STATUS_PENDING %}
                                    <div class="buttons are-small">
                                        <a class="button is-outlined is-primary"
                                            href="{% url 'register:order_cancel_button_on_list_orders' item.pk %}">Cancelar</a>
                                    </div>
                                    {% elif item.status == item.STATUS_PREPARING %}
                                    <div class="buttons are-small">
                                        <a class="button is-outlined is-primary"
                                            href="{% url 'register:order_cancel_button_on_list_orders' item.pk %}">Cancelar</a>
                                    </div>
                                    {% endif %}
                                </td>
                            </tr>
                            {% empty %}
                            <tr>
                                <td>Sem Pedidos</td>
                                <td></td>
                                <td></td>
                                <td></td>
                                <td></td>
                                <td></td>
                            </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                    {% if is_paginated %}
                    {% include 'pagination.html' %}
                    {% endif %}
                </div>
            </div>
        </div>
    </div>
</div>
<div class="modal">
    <div class="modal-background"></div>
    <div class="modal-content"></div>
    <button class="modal-close is-large" aria-label="close"></button>
</div>

{% comment %}
{% if item.status == item.STATUS_PENDING %}
<a href="{% url 'register:order_kitchen_accepted_at' item.pk %}"> Aceitar ou Rejeitar Pedido </a>

{% elif item.status == item.STATUS_REJECTED %}
Essa pedido foi cancelada às: {{ item.canceled_at|date:'g:i a' }}

{% elif item.status == item.STATUS_PREPARING %}
Esse pedido foi aceito às: {{ item.kitchen_accepted_at|date:'g:i a' }}
<a href="{% url 'register:order_kitchen_accepted_at' item.pk %}"> Finalizar ou Cancelar Pedido </a>

{% elif item.status == item.STATUS_DONE %}
Esse pedido foi finalizado às: {{ item.kitchen_finished_at|date:'g:i a' }}

{% endif %}
{% endcomment %}

{% endblock %}

{% block extra-js %}
<script>

    $.urlParam = function (name) {
        var results = new RegExp('[\?&]' + name + '=([^&#]*)').exec(window.location.href);
        if (results == null) {
            return null;
        }
        return decodeURI(results[1]) || 0;
    }

    {% if request.resolver_match.url_name == "orders_filter_by_table" %}
    $('select[name=table]').val($.urlParam('table'));
    {% endif %}

    $('select[name=table]').change(function () {
        $('form#searchform').submit();
    })

    var confirm_order_url = "";

    function createOrder(url) {

        confirm_order_url = url;

        $.get(url, function () {
            //console.log(url);
        })

            .done(function (data) {
                //console.log(data);
                $(".modal > .modal-content").html(data);
                $(".modal").addClass("is-active");
                $(".modal .modal-content button.is-danger").click(function () {
                    $(".modal").removeClass("is-active");
                });
            })

            .fail(function (xhr) {
            });

        $(".modal-close, .modal-background").click(function () {
            $(this).parents(".modal").removeClass("is-active");
        });
    }

    function submitOrder() {
        $.post(confirm_order_url, $('#order-form').serialize())

            .done(function (data) {
                location.reload();
            })

            .fail(function (xhr) {
                console.log("Error: ", xhr);
            });
    }

    function closeModal(event) {
        $(".modal").removeClass("is-active");
    }



</script>
{% endblock %}

register/templates/components/kitchen/orders_card.html
{% load humanize %}
{% load load_permissions %}

<div class="column is-one-third-desktop is-4-tablet">
  <div id="kitchen-cards"
    class="card categorie{% if request.resolver_match.url_name == "orders_kitchen_category_filter" %}{% for category in categories_filter %}{{category.id}}{% endfor %}{% else %}{% endif %} ">
    <div class="card-content has-padb-1">
      <div class="level is-marginless">
        <div class="level-left">
          <div class="level-item">
            <p class="title is-5 has-text-info has-text-weight-normal">
              {% if order.bill.table.name == 'order_remote' %}
                Retirar no Balcao
              {% else %}
                {{ order.bill.table.name }}
              {% endif %}
            </p>
          </div>
        </div>
        <div class="level-right">
          <div class="level-item">
            <p class="title is-4 has-text-weight-normal">#{{ order.id }}</p>
          </div>
        </div>
      </div>
      <div class="level is-border-bottom has-padb-2">
        <div class="level-left">
          <div class="level-item">
            <p class="subtitle is-6">{{ order.user.first_name|default:"Cliente" }}</p>
          </div>
        </div>
        <div class="level-right">
          <div class="level-item">
            <p class="subtitle is-7">{{order.created_at}}</p>
          </div>
        </div>
      </div>
      <p class="is-size-5 has-text-weight-normal"><strong>{{order.quantity}}x</strong> {{ order.item.name }}</p>
      {% if order.item.observartions  %}
      <a class="button is-primary" title="Tag" disabled>{{order.item.observartions}}</a>
      {% endif %}
      <p class="is-size-7 min-10 has-text-weight-normal">{{ order.observation }}</p>
      <p class="is-size-6 has-text-weight-normal has-magb-2">Conta <strong>#{{ order.bill.id }}</strong></p>
    </div>
    {% if order.status == order.STATUS_PENDING %}
    <div class="column">
      <div class="columns is-mobile is-centered">
        <div class="column is-two-fifths">
          <a href="{% url 'register:order_kitchen_cancel' order.pk %}" class="button is-outlined is-danger is-fullwidth"
            onclick="ExcludeOnCard()">Recusar</a>
        </div>
        <div class="column is-two-fifths">
          <a href="{% url 'register:order_kitchen_accepted_at' order.pk %}"
            class="button is-success is-fullwidth">Aceitar</a>
        </div>
      </div>
    </div>
    {% elif order.status == order.STATUS_PREPARING %}
    <div class="column has-text-centered">
      <p class="title is-7 has-text-weight-normal"> Esse pedido foi aceito às:
        {{ order.kitchen_accepted_at|naturaltime }} </p>
      <div class="columns is-centered">
        <div class="column is-half">
          <a href="{% url 'register:order_kitchen_done' order.pk %}" class="button is-success is-fullwidth">Pronto</a>
        </div>
      </div>
    </div>
    {% endif %}
  </div>
  </div>